apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx_conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      server{
      auth_basic   "Administrator’s Area";
      auth_basic_user_file conf/.htpasswd;
        listen 80;
        server_name localhost;

        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          }
        }
     }
